### ISSUE TITLE
参照先のリンク切れ

### ISSUE THREAD

**Issue by mikoim** [kimyan/TfIdf#1]
新URLはこちら．

TF-IDFで文書内の単語の重み付け | takuti.me
http://takuti.me/note/tf-idf/

**Comment by koyakimu** [comment]
直しました。
あざす。

研究室で使うように急いで作ったやつなので、適当にブランチ切ってリファクタリングしてくれていいよー
（MoTfIdfのMoとかなんで付いてるのか謎だし）
